apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-1-local
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: app-1-local-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: app-1-local-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/IdanHenik/argocd-dr.git
        targetRevision: main
        path: apps/app-1
      destination:
        namespace: default
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: app-1-local-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default

