apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-reload-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
       #serviceAccountName: argo-hooker
       containers:
       - name: pod-deletion-container
         image: openshift/origin-cli:latest
         command: ["/bin/bash", "-c"]
         args:
         - |
            oc login -u admin -p xT91nh2fVgwMT8kA --server=https://api.cluster-x7psm.x7psm.sandbox2348.opentlc.com:6443 --insecure-skip-tls-verify
            oc scale replicaset --all --replicas=0
            sleep 3
            oc scale replicaset --all --replicas=1
            oc login -u admin -p DRFVabLmdrQK4uQ4 --server=https://api.cluster-dwdxz.dwdxz.sandbox2869.opentlc.com:6443 --insecure-skip-tls-verify
            oc scale replicaset --all --replicas=0
            sleep 3
            oc scale replicaset --all --replicas=1
       restartPolicy: Never
    backoffLimit: 1
